import os
import io
from typing import List
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse, StreamingResponse
from sqlalchemy.orm import Session
from app.database import get_db
from app.models import GalleryItem, User, Project
from app.schemas import GenerateRequest, GalleryItemOut
from app.auth import get_current_user
from app.config import get_settings

router = APIRouter(prefix="/gallery", tags=["gallery"])
settings = get_settings()


@router.get("/{project_id}", response_model=List[GalleryItemOut])
def list_gallery(
    project_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    items = db.query(GalleryItem).filter(GalleryItem.project_id == project_id)\
               .order_by(GalleryItem.created_at.desc()).all()
    return [GalleryItemOut.model_validate(i) for i in items]


@router.post("/generate", response_model=GalleryItemOut, status_code=201)
def generate_output(
    data: GenerateRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    project = db.query(Project).filter(Project.id == data.project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    gallery_dir = os.path.join(settings.upload_dir, data.project_id, "gallery")
    os.makedirs(gallery_dir, exist_ok=True)

    import uuid
    item_id = str(uuid.uuid4())
    file_size = 0
    file_path = None

    try:
        if data.output_type == "pdf":
            file_path, file_size = _generate_pdf(data.title, data.content or "", gallery_dir, item_id)
        elif data.output_type == "ppt":
            file_path, file_size = _generate_pptx(data.title, data.content or "", gallery_dir, item_id)
        elif data.output_type == "notes":
            file_path, file_size = _generate_notes(data.title, data.content or "", gallery_dir, item_id)
        elif data.output_type == "quiz":
            file_path, file_size = _generate_quiz(data.title, data.content or "", gallery_dir, item_id)
    except Exception as e:
        # Fallback: create a simple text file
        file_path = os.path.join(gallery_dir, f"{item_id}.txt")
        content_text = f"{data.title}\n\nGenerated by CollabMind AI\n\n{data.content or 'Content placeholder'}"
        with open(file_path, "w") as f:
            f.write(content_text)
        file_size = os.path.getsize(file_path)

    item = GalleryItem(
        id=item_id,
        project_id=data.project_id,
        output_type=data.output_type,
        title=data.title,
        file_path=file_path,
        file_size=file_size,
        item_metadata={"generated_by": "CollabMind AI", "version": "1.0"},
    )
    db.add(item)
    db.commit()
    db.refresh(item)
    
    return GalleryItemOut.model_validate(item)


@router.get("/download/{item_id}")
def download_gallery_item(
    item_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    item = db.query(GalleryItem).filter(GalleryItem.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    
    if not item.file_path or not os.path.exists(item.file_path):
        raise HTTPException(status_code=404, detail="File not found on storage")

    filename_map = {"pdf": ".pdf", "ppt": ".pptx", "notes": ".pdf", "quiz": ".pdf"}
    ext = filename_map.get(item.output_type, ".txt")
    mime_map = {
        "pdf": "application/pdf",
        "ppt": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "notes": "application/pdf", "quiz": "application/pdf",
    }
    media_type = mime_map.get(item.output_type, "application/octet-stream")
    
    filename = f"{item.title.replace(' ', '_')}{ext}"
    return FileResponse(path=item.file_path, filename=filename, media_type=media_type)


@router.get("/preview/{item_id}")
def preview_gallery_item(
    item_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    item = db.query(GalleryItem).filter(GalleryItem.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    
    if not item.file_path or not os.path.exists(item.file_path):
        raise HTTPException(status_code=404, detail="File not available for preview")

    mime_map = {
        "pdf": "application/pdf", "notes": "application/pdf", "quiz": "application/pdf",
        "ppt": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    }
    media_type = mime_map.get(item.output_type, "application/octet-stream")
    return FileResponse(path=item.file_path, media_type=media_type)


@router.delete("/{item_id}", status_code=204)
def delete_gallery_item(
    item_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    item = db.query(GalleryItem).filter(GalleryItem.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    
    project = db.query(Project).filter(
        Project.id == item.project_id, Project.owner_id == current_user.id
    ).first()
    if not project:
        raise HTTPException(status_code=403, detail="Access denied")
    
    if item.file_path and os.path.exists(item.file_path):
        os.remove(item.file_path)
    
    db.delete(item)
    db.commit()


# ─── Generators ───────────────────────────────────────────────────────────────
def _generate_pdf(title: str, content: str, out_dir: str, item_id: str):
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.units import inch

        path = os.path.join(out_dir, f"{item_id}.pdf")
        doc = SimpleDocTemplate(path, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, spaceAfter=20)
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.2 * inch))

        # Subtitle
        story.append(Paragraph("Generated by CollabMind AI", styles["Italic"]))
        story.append(Paragraph(datetime.now().strftime("%B %d, %Y"), styles["Normal"]))
        story.append(Spacer(1, 0.4 * inch))

        # Content
        if content:
            for para in content.split("\n"):
                if para.strip():
                    story.append(Paragraph(para.strip(), styles["Normal"]))
                    story.append(Spacer(1, 0.1 * inch))
        else:
            story.append(Paragraph(
                "This document was generated from your CollabMind AI knowledge base. "
                "Upload documents and use the Generate PDF button to create grounded content.",
                styles["Normal"]
            ))

        doc.build(story)
        return path, os.path.getsize(path)
    except ImportError:
        raise Exception("reportlab not available")


def _generate_pptx(title: str, content: str, out_dir: str, item_id: str):
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt

        path = os.path.join(out_dir, f"{item_id}.pptx")
        prs = Presentation()
        
        # Title slide
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by CollabMind AI"

        # Content slides
        lines = [l.strip() for l in (content or "Add content here").split("\n") if l.strip()]
        
        for i in range(0, max(len(lines), 3), 3):
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = f"Section {i // 3 + 1}"
            body = slide.placeholders[1]
            tf = body.text_frame
            tf.text = lines[i] if i < len(lines) else "Content"
            for j in range(1, 3):
                if i + j < len(lines):
                    p = tf.add_paragraph()
                    p.text = lines[i + j]

        prs.save(path)
        return path, os.path.getsize(path)
    except ImportError:
        raise Exception("python-pptx not available")


def _generate_notes(title: str, content: str, out_dir: str, item_id: str):
    # Notes are also PDFs with structured formatting
    notes_content = f"Study Notes: {title}\n\nKey Points:\n• " + "\n• ".join(
        [l.strip() for l in (content or "Summarized notes from your documents").split("\n") if l.strip()][:10]
    )
    return _generate_pdf(f"Notes: {title}", notes_content, out_dir, item_id)


def _generate_quiz(title: str, content: str, out_dir: str, item_id: str):
    quiz_content = f"""Quiz: {title}

Instructions: Answer all questions based on the uploaded materials.

Q1. What is the main concept discussed in the documents?
   a) Option A
   b) Option B
   c) Option C  
   d) Option D

Q2. Which approach is recommended for this topic?
   a) First approach
   b) Second approach
   c) Third approach
   d) None of the above

Q3. What are the key benefits mentioned?
   a) Speed and efficiency
   b) Cost reduction
   c) Quality improvement
   d) All of the above

Q4. What is the primary use case?
   a) Research
   b) Production
   c) Testing
   d) Development

Q5. According to the sources, what is the recommended next step?
   a) Further research
   b) Implementation
   c) Review
   d) Deployment

---
Score: ____ / 5
"""
    return _generate_pdf(f"Quiz: {title}", quiz_content, out_dir, item_id)
